### ISSUE TITLE
micode.net seems to be down

### ISSUE THREAD

**Issue by nnn1590** [MiCode/patchrom_miui#41]
The link described in this repository (http://micode.net/forum-59-1.html) seems to be down.  
Was it replaced by a new link? Or has it been abolished?
___
このレポジトリに記載されているリンク(http://micode.net/forum-59-1.html) はダウンしているようです。  
それは新しいリンクに置換されましたか？もしくは廃止されてしまいましたか？

**Comment by yuanphoenix** [comment]
abolished

**Comment by nnn1590** [comment]
Thank you for answering!

**Comment by Jinansh23** [comment]
If you need help search micode.net in web.archive.net and use Google Translate to understand.
