### ISSUE TITLE
About the translation

### ISSUE THREAD

**Issue by axel2033** [MiCode/patchrom_miui#6]
Hi)
Why do not you add to your applications translate other languages?
https://github.com/miuirussia/miui-v4-russian-translation It is translation It is the Russian translation for miui.
Please merge it and other lanuages in your parts of miui)
If you add back a lot of languages​​, you will be doubly grateful all planet)

**Comment by iBotPeaches** [comment]
Thats what all fansites are for :p

The ROM with all languages would be huge. Simply adding one language adds near 5mb.

**Comment by axel2033** [comment]
Ok. Thanks for your answer;)
