### ISSUE TITLE
About Galaxy nexus

### ISSUE THREAD

**Issue by axel2033** [MiCode/patchrom_miui#7]
Do you build firmware for thias device from source with wiui changes like for mi one or change system with help of patchrom?

**Comment by iBotPeaches** [comment]
The GNEX, Mi One, Nexus S and HTC One X are all source built (Hence less bugs in them :p)

The Sensation, Honor, Arc and SGS2 are patchrom built.

**Comment by axel2033** [comment]
Great thank you)))))
But how can you build one x from source?
Gnex, nexus s are open sources devices with open for all configs and without proprietatity files.
HTC don't put to publik configs for build ftom sources.
How do you build it?

**Comment by iBotPeaches** [comment]
One X is in beta testing by Xiaomi right now. Releases will come. 

You can get kernel files from HTCDev http://www.htcdev.com/

**Comment by axel2033** [comment]
no no no 
I asked about configs like this https://github.com/CyanogenMod/android_device_htc_ace for building from sources

**Comment by iBotPeaches** [comment]
Thats a raw Cyanogenmod repo. That takes time. There is no public one for the HTC One X.

**Comment by axel2033** [comment]
Thanks)

**Comment by axel2033** [comment]
Do you use stock kernels for miui or you make changes in kernel?
